#!/usr/bin/env python

try:
    import tkinter as tk
    import tkinter.font as tkFont
    import tkinter.ttk as ttk
except ImportError:  # Python 2
    import Tkinter as tk
    import tkFont
    import ttk


class Widget:

    def add_widget(self, widget):
        if not hasattr(self, gm):
            raise AttributeError("The widget subclass must define a"
                                 " Tkinder geometry manager.")
        if self.gm == "grid":
            widget.atI = self.layoutI
            if self.orientation == "horizontal":
                widget.grid(column=self.layoutI, row=0,
                            sticky=tk.N+tk.S)
            elif self.orientation == "vertical":
                widget.grid(column=0, row=self.layoutI,
                            sticky=tk.W+tk.E)
            else:
                raise ValueError("Unknown Kivy orientaton: {}"
                                 "".format(self.orientation))
            self.layoutI += 1
        else:
            raise ValueError("A Tkinter geometry manager named {} is"
                             " not implemented.".format(self.gm))
